#!/usr/bin/env python3
"""Generate TID's speaker symbol: two 24 x 24 A8 marks, sound on and off.

A8 so the view can recolour it with the palette; pixels are 255 or 0. Run
this file to regenerate components/app_time/speaker_assets.{h,c};
test_build_speaker_assets.py fails when the checked-in sources drift."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT_H = ROOT / "components/app_time/speaker_assets.h"
OUT_C = ROOT / "components/app_time/speaker_assets.c"
SIZE = 24


def _speaker() -> set[tuple[int, int]]:
    """The box and the cone, open to the right."""
    on = {(x, y) for x in range(3, 8) for y in range(9, 15)}
    for x in range(8, 14):
        spread = x - 8  # the cone widens one row up and down per column
        on |= {(x, y) for y in range(9 - spread, 15 + spread)}
    return on


def _waves() -> set[tuple[int, int]]:
    """Two arcs to the right of the cone, radius 5 and 8 around (12, 12)."""
    on = set()
    for x in range(16, SIZE):
        for y in range(SIZE):
            d2 = (x - 12) ** 2 + (y - 12) ** 2
            for r in (5.5, 8.5):
                if (r - 0.9) ** 2 <= d2 <= (r + 0.6) ** 2 and abs(y - 12) <= r * 0.75:
                    on.add((x, y))
    return on


def _slash() -> set[tuple[int, int]]:
    """A 2 px diagonal where the waves would be."""
    on = set()
    for i in range(11):
        x, y = 13 + i * 9 // 10, 6 + i
        on |= {(x, y), (x + 1, y)}
    return {(x, y) for x, y in on if 0 <= x < SIZE and 0 <= y < SIZE}


def _encode(pixels: set[tuple[int, int]]) -> bytes:
    return bytes(255 if (x, y) in pixels else 0
                 for y in range(SIZE) for x in range(SIZE))


def build_assets() -> dict[str, bytes]:
    return {
        "on": _encode(_speaker() | _waves()),
        "off": _encode(_speaker() | _slash()),
    }


def _c_array(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 24):
        chunk = data[offset:offset + 24]
        rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};\n"


def _descriptor(name: str, data_name: str, size: int) -> str:
    return f"""const lv_image_dsc_t {name} = {{
  .header = {{
    .magic = LV_IMAGE_HEADER_MAGIC,
    .cf = LV_COLOR_FORMAT_A8,
    .flags = 0,
    .w = {SIZE},
    .h = {SIZE},
    .stride = {SIZE},
  }},
  .data_size = {size},
  .data = {data_name},
}};
"""


def render_sources() -> tuple[str, str]:
    assets = build_assets()
    header = """#ifndef TORGET_SPEAKER_ASSETS_H
#define TORGET_SPEAKER_ASSETS_H

#include "lvgl.h"

/* Generated by tools/speaker_assets/build_speaker_assets.py. */
extern const lv_image_dsc_t tg_img_speaker_on;
extern const lv_image_dsc_t tg_img_speaker_off;

#endif
"""
    source = '#include "speaker_assets.h"\n\n'
    for state, data in assets.items():
        source += _c_array(f"tg_img_speaker_{state}_data", data)
    source += "\n"
    for state, data in assets.items():
        source += _descriptor(f"tg_img_speaker_{state}",
                              f"tg_img_speaker_{state}_data", len(data))
    return header, source


def main() -> None:
    header, source = render_sources()
    OUT_H.write_text(header, encoding="utf-8")
    OUT_C.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
