#ifndef TORGET_SPEAKER_ASSETS_H
#define TORGET_SPEAKER_ASSETS_H

#include "lvgl.h"

/* Generated by tools/speaker_assets/build_speaker_assets.py. */
extern const lv_image_dsc_t tg_img_speaker_on;
extern const lv_image_dsc_t tg_img_speaker_off;

#endif
